### ISSUE TITLE
Tag description with special character does not render correctly

### ISSUE THREAD

**Issue by hayos** [omnifaces/vdldoc#14] opened 2017-11-22 15:42 UTC
At least the special characters &amp;lt; (<)  and &amp;gt;  (>) and the content in between are not rendered correctly into the html output.

Example:

&lt;tag&gt;
  &lt;description&gt;deprecated. Use &amp;lt;base:commandButtonFixId&amp;gt; instead.&lt;/description&gt;

The output rendered into the html is: " Use &lt;base:dialogFixId&gt; instead."
The output in the browser actually is: "Use instead."

This is because the content is turned into an invalid tag. Instead special characters in description should stay special characters. Or to be exact: Turned into the real character and then turned into escaped html.

When fixing please check also  &amp;amp; (&), &amp;quot; ("), and &amp;apos; (').

**Comment by stiemannkj1** [comment] 2017-11-22 15:47
@hayos, that's by design so that people can use HTML in their documentation. Use [HTML escape characters (like `&lt;` instead of `<`)](https://stackoverflow.com/questions/7381974/which-characters-need-to-be-escaped-on-html) when you want to show special XML characters.

**Comment by stiemannkj1** [comment] 2017-11-22 15:52
@hayos, can you provide a **`*.taglib.xml`** file that reproduces this error. It seems to work fine for the Liferay Faces taglibs.

Input:
https://github.com/liferay/liferay-faces-alloy/blob/master/alloy/src/main/resources/META-INF/alloy.taglib.xml#L93

Output:
http://liferayfaces.org/doc/faces/vdldoc/alloy/3.0/alloy/audio.html

**Comment by stiemannkj1** [comment] 2017-11-22 15:54
Perhaps you need to surround your `<description>` with `<![CDATA[` `]]>` tags.

**Comment by hayos** [comment] 2017-11-22 16:00
Why is the "invalid" label set before I am ready? And I cannot change that.
This is a _valid_ **Bug** report for *taglib.xml documentation rendering.

**Comment by stiemannkj1** [comment] 2017-11-22 16:04
@hayos, Sorry, I removed the label, the email for this issue was weird due to XML escaping issues, so I misread the question. That being said, this is still likely invalid and surrounding your description with CDATA would likely fix the problem.

**Comment by hayos** [comment] 2017-11-22 16:10
You are too fast for me ;-).

"Use &lt;![CDATA[&amp;lt;base:commandButtonFixId&gt;]]&gt; instead." 
renders indeed to
"Use &lt;base:commandButtonFixId&gt; instead. "

**Comment by hayos** [comment] 2017-11-22 16:16
Please see example in http://xml.silmaril.ie/cdata.html .
You would normally use CDATA like that:
"some text with &lt;![CDATA[&lt;em&gt;markup&lt/em&gt;]]&gt; in it."

So your proposed way to do it as I tried out above seems to work, but actually does not. Because in my opinion that code in my answer before should render to "Use &amp;lt;base:commandButtonFixId&amp;gt; instead. "

**Comment by stiemannkj1** [comment] 2017-11-22 16:30
@hayos, glad I could help, closing the issue as invalid as vdldoc is behaving correctly. Surround your descriptions with CDATA in order to propagate escaped XML characters to the markup. Note that when CDATA is used, you can also use HTML tags. For example, "&lt;code&gt;\&lt;base:commandButtonFixId\&gt;&lt;/code&gt;" is rendered as `<base:commandButtonFixId>` in the browser. However when CDATA is not used, escaped XML characters are rendered in their unescaped form in the rendered HTML. You should be able to escape both the ampersand and the character (for example `&amp;lt;`) to ensure that it is rendered correctly in the HTML (although using CDATA is much easier). I believe this is due to how XML parsing (and `SAXParser`) works by default.

**Closed by stiemannkj1** 2017-11-22 16:30 UTC
Labels: invalid

**Comment by hayos** [comment] 2017-11-22 17:17
I excerpted the first tag from an actually larger taglib.xml and attached it here. 
[baseexcerpt.taglib.xml.txt](https://github.com/omnifaces/vdldoc/files/1496896/baseexcerpt.taglib.xml.txt)
But you will find that even in that one file once your CDATA approach is used and once my favorized 
approach.

Regarding the LifeRay documentation: Please take into account that it could be the case that the code is written in that way in order to support Vdldoc as it is. The contained 'xmlns:vdldoc="http://vdldoc.omnifaces.org"' makes me assume that they wrote the code so that it works.

If you look into the documentation of c-10.tld ([c-1_0.tld.txt](https://github.com/omnifaces/vdldoc/files/1496926/c-1_0.tld.txt)) in tag choose you'll see that Sun (now Apache) uses my approach. If you then go to Oracle's official documentation you will see how that renders with the tlddoc: https://docs.oracle.com/javaee/6/javaserverfaces/2.0/docs/pdldocs/facelets/c/choose.html
Yes, the content rendered incorrectly for ages.

So I think I my point is valid. But that should be proven by checking original description tags by  Sun/Oracle in all types of tag libraries. 

But: That would break other people' documentation like LifeRay's. So the only nice way to implement it would be an option.

**Comment by hayos** [comment] 2017-11-22 17:47
However, thank you very much for your quick support. It helped to clearly find the cause of my problem.

**Comment by stiemannkj1** [comment] 2017-11-22 17:51
@hayos, when I look at the c-10.tld you sent, I see that they are using escaped XML characters like`&lt;` in the description in the same way that you did:

```
<description>
	Simple conditional tag that establishes a context for
	mutually exclusive conditional operations, marked by
	&lt;when&gt; and &lt;otherwise&gt;
</description>
```

But when I look at the linked output (https://docs.oracle.com/javaee/6/javaserverfaces/2.0/docs/pdldocs/facelets/c/choose.html), it is rendered the same way that VDLDoc renders escaped XML characters. It appears in the browser like so:

> Simple conditional tag that establishes a context for mutually exclusive conditional operations, marked by <when> and <otherwise>

So VDLDoc's behavior is consistent with the TLDDoc generator's behavior. This is as expected since VDLDoc was forked from the TLDDoc generator a long time ago. This proves that the generator's behavior is correct and **the documentation should be fixed** instead.

As for the idea of adding an option, why isn't simply wrapping the content in CDATA (or double escaping the content) good enough? It seems just about as easy as setting an option.

Note that Mojarra, the official JSF reference implementation, uses the CDATA approach as well: https://github.com/javaserverfaces/mojarra/blob/master/jsf-ri/conf/share/html_basic.taglib.xml#L56
